# Generated by Django 2.2.6 on 2019-10-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default='user', max_length=64),
            preserve_default=False,
        ),
    ]
